name: "添加/更新小白条规则"
description: "在 module/immerse_rules.xml 文件中添加或修改（若包名已存在）规则，提交Issue后将会自动创建对应PR（通常需要10s左右）"
title: "规则更新: [应用名]"
labels: ["自动化请求", "规则更新"]
body:
  - type: input
    id: app_name
    attributes:
      label: "应用名"
      description: "请输入应用名（系统`应用信息|应用详情`界面中的`应用名称`）"
      placeholder: "Example"
    validations:
      required: true
  - type: input
    id: package_name
    attributes:
      label: "包名"
      description: "请输入应用包名"
      placeholder: "com.example.app"
    validations:
      required: true
  - type: input
    id: activity_rule
    attributes:
      label: "Activity规则"
      description: "请输入Activity规则，格式为 Activity ID:适配方式，参见[适配规则](https://github.com/Ianzb/MiNavBarImmerse/blob/main/rule.md)"
      placeholder: "*:2,com.example.MainActivity:1:-16777216"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "修改说明"
      description: "请描述此次修改的原因和目的。可选"
      placeholder: "为XX应用添加规则适配..."
  - type: input
    id: user_email
    attributes:
      label: "您的邮箱"
      description: "请输入您的邮箱地址，用于在提交记录中标识贡献者。可选，未填写则使用github noreply邮箱"
      placeholder: "your.email@example.com"
    validations:
      required: false
